# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customID', models.CharField(max_length=100)),
                ('customName', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=100)),
                ('taxFileNO', models.CharField(max_length=100)),
                ('bankOfDepsit', models.CharField(max_length=100)),
                ('bankAccount', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('industryField', models.CharField(max_length=100)),
                ('companyNature', models.CharField(max_length=100)),
                ('gasCategory', models.CharField(max_length=100)),
                ('consocationMode', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=100)),
                ('payCycle', models.DateField()),
                ('companyCharge', models.CharField(max_length=100)),
                ('companyContact', models.CharField(max_length=100)),
                ('customQualification', models.CharField(max_length=100)),
                ('annualSales', models.CharField(max_length=100)),
            ],
        ),
    ]
